import { describe, expect, test } from "bun:test";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { updateGraph } from "./graph.ts";
import { rootsPaths } from "./paths.ts";
import {
	forceStatus,
	initProject,
	patchConfig,
	plant,
	run,
	runJson,
	spawnCli,
} from "./test-helpers.ts";
import type { EdgeRel } from "./types.ts";

let edgeSeq = 0;
async function link(root: string, from: string, to: string, rel: EdgeRel) {
	edgeSeq++;
	await updateGraph(rootsPaths(root), (g) => {
		g.edges.push({
			type: "edge",
			id: `e-${String(edgeSeq).padStart(4, "0")}`,
			from,
			to,
			rel,
			by: "human:t",
			createdAt: `2026-01-01T00:00:${String(edgeSeq % 60).padStart(2, "0")}Z`,
		});
		return { write: true, result: null };
	});
}

function ideaFile(root: string, id: string): string {
	const hex = id.slice(2);
	const dir = join(root, ".roots", "human");
	const name = readdirSync(dir).find((n) => n.startsWith(`${hex}-`)) ?? "";
	return join(dir, name);
}

/**
 *   goal (committed)  ← sync (shaping) ← queue (planted) → auth (shaping)
 *   sync ↔ auth tension; gone composted (serves goal); lonely planted
 */
async function fixture() {
	const root = await initProject();
	const goal = await plant(root, "Field users never lose work", ["--slug", "goal"]);
	const sync = await plant(root, "Sync works offline", ["--slug", "sync"]);
	const queue = await plant(root, "Writes go to a local queue first", ["--slug", "queue"]);
	const auth = await plant(root, "The server is always authoritative", ["--slug", "auth"]);
	const gone = await plant(root, "An old retired idea", ["--slug", "gone"]);
	const lonely = await plant(root, "Maybe dark mode", ["--slug", "lonely"]);
	await link(root, sync, goal, "serves");
	await link(root, queue, sync, "serves");
	await link(root, queue, auth, "serves");
	await link(root, gone, goal, "serves");
	await link(root, sync, auth, "tension");
	await forceStatus(root, goal, "committed");
	await forceStatus(root, sync, "shaping");
	await forceStatus(root, auth, "shaping");
	await forceStatus(root, gone, "composted");
	writeFileSync(
		join(ideaFile(root, goal), "idea.md"),
		"Field users never lose work\n\nThey lose signal for hours.\n",
	);
	return { root, goal, sync, queue, auth, gone, lonely };
}

describe("roots view (markdown)", () => {
	test("anchors, depth-first serves, back-references, tensions, unanchored", async () => {
		const f = await fixture();
		const r = await run(["view"], f.root);
		expect(r.exitCode).toBe(0);
		const md = r.stdout;
		expect(md.startsWith("<!-- Generated by `roots view`")).toBe(true);
		expect(md).toContain("## Field users never lose work");
		expect(md).toContain("They lose signal for hours.");
		expect(md).toContain("### Sync works offline");
		expect(md).toContain("#### Writes go to a local queue first");
		expect(md).toContain("## The server is always authoritative");
		// queue serves both sync and auth: printed once, then referenced.
		expect(md.match(/# Writes go to a local queue first/g)?.length).toBe(1);
		expect(md).toContain(
			`↑ Also serves this: **Writes go to a local queue first** (\`${f.queue}\`)`,
		);
		// order: goal tree before auth tree
		expect(md.indexOf("## Field users")).toBeLessThan(md.indexOf("## The server"));
		expect(md).toContain("## Tensions");
		expect(md).toContain(
			`**Sync works offline** (\`${f.sync}\`) ↔ **The server is always authoritative** (\`${f.auth}\`)`,
		);
		expect(md).toContain("## Not yet under an anchor");
		expect(md).toContain(`- Maybe dark mode (\`${f.lonely}\` · planted)`);
		// composted excluded everywhere
		expect(md).not.toContain("An old retired idea");
		expect(md).not.toContain("Agent proposals");
		expect(r.stdout).not.toMatch(/\d{4}-\d{2}-\d{2}T/);
	});

	test("open questions are listed; agent-asked ones are labeled [agent]", async () => {
		const f = await fixture();
		const asked = await runJson(["ask", f.sync, "What if two devices edit offline?"], f.root, {
			env: { ROOTS_AGENT: "agent:test" },
			tty: false,
		});
		expect(asked.exitCode).toBe(0);
		const md = (await run(["view"], f.root)).stdout;
		expect(md).toContain("## Open questions");
		expect(md).toContain(
			`- \`${f.sync}\` sync: What if two devices edit offline? _([agent] agent:test)_`,
		);
	});

	test("--sprouts appends a separate [agent] section; sprouts never appear otherwise", async () => {
		const f = await fixture();
		const s = await runJson(["sprout", "Conflicts get a merge screen"], f.root, {
			env: { ROOTS_AGENT: "agent:test" },
			tty: false,
		});
		expect(s.exitCode).toBe(0);
		expect((await run(["view"], f.root)).stdout).not.toContain("Conflicts get a merge screen");
		const md = (await run(["view", "--sprouts"], f.root)).stdout;
		const at = md.indexOf("## Agent proposals (not accepted)");
		expect(at).toBeGreaterThan(md.indexOf("## Tensions"));
		expect(md.slice(at)).toContain("### [agent] Conflicts get a merge screen");
		expect(md.slice(at)).toContain("proposed by agent:test");
	});

	test("--from starts at one idea; composted --from is refused", async () => {
		const f = await fixture();
		const md = (await run(["view", "--from", "sync"], f.root)).stdout;
		expect(md).toContain("## Sync works offline");
		expect(md).toContain("### Writes go to a local queue first");
		expect(md).not.toContain("Field users");
		expect(md).not.toContain("Not yet under an anchor");
		const bad = await runJson(["view", "--from", "gone"], f.root);
		expect(bad.exitCode).toBe(2);
	});

	test("deterministic: same data, same bytes; view.write keeps ROOTS.md in step", async () => {
		const f = await fixture();
		const a = (await run(["view"], f.root)).stdout;
		const b = (await run(["view"], f.root)).stdout;
		expect(a).toBe(b);
		const rootsMd = join(f.root, "ROOTS.md");
		expect(existsSync(rootsMd)).toBe(false);
		await patchConfig(f.root, { view: { write: true } });
		// Flags do not change ROOTS.md: it is always the canonical view.
		const r = await run(["view", "--sprouts", "--from", "sync"], f.root);
		expect(r.stderr).toContain("updated ROOTS.md");
		expect(readFileSync(rootsMd, "utf8")).toBe(a);
		const mtime = statSync(rootsMd).mtimeMs;
		const again = await run(["view"], f.root);
		expect(again.stderr).not.toContain("updated ROOTS.md");
		expect(statSync(rootsMd).mtimeMs).toBe(mtime);
	});

	test("--json returns the structured view; --out writes a file, never into human/", async () => {
		const f = await fixture();
		const r = await runJson<{
			tree: { id: string; children: { id: string }[] }[];
			unanchored: { id: string }[];
			tensions: { a: string; b: string }[];
			ideas: Record<string, { statement: string }>;
			text: string;
		}>(["view"], f.root);
		expect(r.body.tree.map((t) => t.id)).toEqual([f.goal, f.auth]);
		expect(r.body.tree[0]?.children.map((c) => c.id)).toEqual([f.sync]);
		expect(r.body.unanchored.map((u) => u.id)).toEqual([f.lonely]);
		expect(r.body.tensions).toEqual([expect.objectContaining({ a: f.sync, b: f.auth })]);
		expect(r.body.ideas[f.gone]).toBeUndefined();
		const out = await run(["view", "--out", "docs.md"], f.root);
		expect(out.exitCode).toBe(0);
		expect(readFileSync(join(f.root, "docs.md"), "utf8")).toBe(r.body.text);
		const guard = await run(["view", "--out", ".roots/human/x.md"], f.root);
		expect(guard.exitCode).toBe(4);
	});

	test("empty project", async () => {
		const root = await initProject();
		const r = await run(["view"], root);
		expect(r.stdout).toContain("(no committed or shaping ideas yet)");
	});

	test("smoke: the real binary", async () => {
		const f = await fixture();
		const r = await spawnCli(["view", "--html"], f.root);
		expect(r.exitCode).toBe(0);
		expect(r.stdout.startsWith("<!doctype html>")).toBe(true);
	});
});
